### ISSUE TITLE
pointed-5.0.{1,2} fails to build with GHC 9.2+

### ISSUE THREAD

**Issue by Bodigrim** [ekmett/pointed#20]
```
$ cabal unpack pointed-5.0.1 && cd pointed-5.0.1 && cabal build -w ghc-9.2
...
Building library for pointed-5.0.2..
[1 of 2] Compiling Data.Copointed
[2 of 2] Compiling Data.Pointed

src/Data/Pointed.hs:207:18: error:
    Not in scope: type constructor or class ‘Option’
    |
207 | instance Pointed Option where
    |                  ^^^^^^
Error: cabal: Failed to build pointed-5.0.1.
```

Same for `pointed-5.0.2`. A revision would be appreciated.

**Comment by RyanGlScott** [comment]
Thanks for the heads-up. The `Pointed Option` was first introduced in `pointed-4.2.0.1`, so I have revised every `pointed` release from `4.2.0.1` to `5.0.2` to have an upper version bound of `base < 4.16`.
